### ISSUE TITLE
Add one ICLR 2024 paper

### ISSUE THREAD

**Issue by EdisonLeeeee** [azminewasi/Awesome-Graph-Research-ICLR2024#1]
Hi,

Thanks for creating this amazing collection. Please kindly include our ICLR paper, which proposes a spiking graph contrastive learning framework to learn binarized 1-bit representations for graphs.

Title: A Graph is Worth 1-bit Spikes: When Graph Contrastive Learning Meets Spiking Neural Networks
OpenReview: https://openreview.net/pdf?id=LnLySuf1vp

Thank you!

**Comment by azminewasi** [comment]
I'm sorry for the miss.
I've added it [here >](https://github.com/azminewasi/Awesome-Graph-Research-ICLR2024#a-graph-is-worth-1-bit-spikes-when-graph-contrastive-learning-meets-spiking-neural-networks)
Thank you very much for the heads-up!
